### PR TITLE
Bravo Six, Going Dark (read blind)

### PR DESCRIPTION
**Pull request by sahil-shubham**
## Changes
- Added a theme switcher
 Desktop view:
 
Screen Shot 2021-05-14 at 23 49 52
Screen Shot 2021-05-14 at 23 49 48
 
 Mobile view:
 
image
image

## Todo 
- The current theme seemed like a dark theme, so I added a light theme for all the light theme fans out. (wait, where are the other light theme fans?) 
noone_here

Would look into few colour schemes over the weekend, and suggest the same here or I can add one in this pull request if you already have something in mind.

### CODE REVIEW

**Comment by mukul-mehta** [comment]
Yo, thanks a ton for the PR, seems great!

**Comment by mukul-mehta** [comment]
Some time ago the designer in me (Whatever the fuck that means xD) tried designing a theme for a SSG. Seeing how good my design skills were, I _obviously_ dropped the plan, but I do have a few leftovers from the Figma design that I think we could use. One of the components was a theme switcher. I really like the colours and I think we could use those for the theme switcher

Here's the theme switcher:
image

The exact colours are:

Turquoise/Green whatever: #09CBCB
Orange (for the sun): #FFB800
Purple: #6F6FFC
Black (for the moon): #111111

**Comment by sahil-shubham** [comment]
Looks really nice, would try implementing it and/or tweaking a few other things.

**Comment by mukul-mehta** [comment]
Lemme add Netlify to the site. Deploy previews for PRs is such a great thing to have

**Comment by mukul-mehta** [comment]
Merging for now, we could make changes later as well

(Also because I want to see if GitHub PRs and Actions is down xD 😛)

**Pull request merged**
